---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: gcp-provider
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  serviceAccountName: gcp-provider
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: kubernetes-provider
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  serviceAccountName: kubernetes-provider