---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: in-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: in-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  credentials:
    source: InjectedIdentity