---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: gcp-provider
spec:
  package: crossplane/provider-gcp:v0.21.0
  controllerConfigRef:
    name: gcp-provider
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: kubernetes-provider
spec:
  package: ghcr.io/mavenwave-devops/provider-kubernetes:v0.5.1
  controllerConfigRef:
    name: kubernetes-provider
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: helm-provider
spec:
  package: ghcr.io/mavenwave-devops/provider-helm:v0.12.1
  controllerConfigRef:
    name: kubernetes-provider